### PR TITLE
Added commands to delete times, users, activities, and projects

### PR DESCRIPTION
**Pull request by aaroncohen73**
@matthewrsj @Kennric Could you review this?

Fixes issues #5 #6 #7 #8

### CODE REVIEW

**Comment by matthewrsj** [comment]
You have the commits from your older PRs in this PR. Please remove.

**Comment by aaroncohen73** [comment]
@matthewrsj The branch no longer contains commits from other PRs

**Comment by ElijahCaine** [comment]
@matthewrsj should check this for correctness, but all of these changes make sense from a logic standpoint and don't collide with my knowledge of how things *should* work in a timesync client.

**Comment by matthewrsj** [comment]
This is correct. I tested it and it all works. +1.

**Pull request merged**
