### PR TITLE
Added support for LDAP authentication

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #89 
Blocked until LDAP support is turned on for the backend

## Changes in this PR.

- [X] Added support for authentication with LDAP

## Testing this PR.

N/A (not supported on the backend yet)

@osuosl/devs

### CODE REVIEW

**Comment by Kennric** [comment]
We're going to need updates to the docs so people know they need to use -l or set ldap = True in their config file

**Comment by subnomo** [comment]
Looks good. :+1:

**Comment by ElijahCaine** [comment]
So to clarify if I add the -l flag it changes some bits in the pymesync usage to use LDAP auth instead of password auth, correct?

I agree with @Kennric, docs updates are always a good thing.

**Comment by subnomo** [comment]
@ElijahCaine Correct.

It would probably be a good idea to ask the user if they are using an LDAP login when signing in, and save the answer to ~/.climesyncrc so you don't have to use the command line flag every time.

**Comment by mathuin** [comment]
@subnomo if this tool is likely to be used in an automated manner, it should probably not ask any questions, just my two cents.

**Comment by subnomo** [comment]
@mathuin We'd only ask on sign-in, if their credentials are already saved then we wouldn't need to.

**Comment by Kennric** [comment]
I think an option to ask would be good, but we need to get this in pretty quickly. @subnomo if you want to implement it, go ahead, otherwise we'll save it for another day. +1

**Comment by subnomo** [comment]
@Kennric I'll create an issue, I doubt I could finish it today.

**Pull request merged**
