### PR TITLE
Clock in/out functionality

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #125 
## Changes in this PR.

- [X] Implemented clock in/out commands
- [x] Added clock in/out commands to scripting mode
## Testing this PR.

1. Run `nosetests` and `flake8 climesync testing`

@osuosl/devs

### CODE REVIEW

**Comment by subnomo** [comment]
Bad things happen when entering activity slugs while clocking in:

```
(h for help) : ci
Slug of project to work on: streams
(Optional) (Comma delimited) Activity slugs: development, research
(Optional) URI of issue in tracker: 
(Optional) Miscellanious notes: 

Clock-in successful
(h for help) : co

project: streams
activities: [u'development',, u'research']
duration: 0h0m
date_worked: 2016-10-06
user: subnomo

(y/n) Does this look correct?: y

status: 400
text: Field activities of time should be slugs but was sent as array containing at least 1 invalid slug
error: Bad object


status: 400
text: Field activities of time should be slugs but was sent as array containing at least 1 invalid slug
error: Bad object
```

Works fine if you're clocking out:

```
(h for help) : ci
Slug of project to work on: streams
(Optional) (Comma delimited) Activity slugs: 
(Optional) URI of issue in tracker: 
(Optional) Miscellanious notes: 

Clock-in successful
(h for help) : co
(Comma delimited) Activities: development, research

project: streams
duration: 0h0m
date_worked: 2016-10-06
user: subnomo
activities: development, research

(y/n) Does this look correct?: y

project: streams
duration: 0h0m
date_worked: 2016-10-06
uuid: 3661e7df-c1c5-4d6b-8398-45bbc39ff707
user: subnomo
```

**Comment by ElijahCaine** [comment]
I haven't put this through it's paces. On initial review I think this looks good *except* it doesn't seem to include a command-line option for clocking in and out. The `clock-in` and `clock-out` options don't show up for me.  I cleaned up any crufty files and it still didn't show up.  I can see in the code that should be included, but in practice... you know.

Let me know if I'm just doing something wrong, the feature works in the REPL though, so that's cool.

**Review by pop — DISMISSED** [review]
I haven't put this through it's paces. On initial review I think this looks good except it doesn't seem to include a command-line option for clocking in and out. The `clock-in` and `clock-out` options don't show up for me. I cleaned up any crufty files and it still didn't show up. I can see in the code that should be included, but in practice... you know.

I haven't put this through it's paces. On initial review I think this looks good except it doesn't seem to include a command-line option for clocking in and out. The clock-in and clock-out options don't show up for me. I cleaned up any crufty files and it still didn't show up. I can see in the code that should be included, but in practice... you know.

Let me know if I'm just doing something wrong, the feature works in the REPL though, so that's cool.

Let me know if I'm just doing something wrong, the feature works in the REPL though, so that's cool.

**Review by subnomo — APPROVED** [review]
Looks good :+1:

**Pull request merged**
