### PR TITLE
Added option to output TimeSync data to a CSV file

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #70 
## Changes in this PR.

- [X] After running a get_\* command, the user is asked if they want to save the result into a CSV file
## Testing this PR.

1. Run `nosetests`
2. Run the program and run the command `gt` to get times without entering any filter parameters.
3. When asked if you want to save the result to a CSV file, type `y` and enter a file name
4. Open that file in your favorite text editor and see that the values have been put into the file in CSV format

@osuosl/devs

### CODE REVIEW

**Comment by Kennric** [comment]
Looks good, resolve conflicts and I will approve.

**Comment by Kennric** [comment]
+1

**Comment by ElijahCaine** [comment]
1. There's currently no default. It should default to (y/N) (no).
2. `[u'test']` should probably just be `['test']`
3. Would it be possible to add an optional <file path> to the ``--csv`` flag? For instance: ``climesync get-times --csv=output.csv``.
4. Rebase.

Otherwise this looks really good.

**Comment by aaroncohen73** [comment]
@ElijahCaine I've addressed all of your other points, but it looks to me like 3 isn't possible with docopt.

**Comment by Kennric** [comment]
Looks good, just needs conflicts resolved. @subnomo

**Comment by Kennric** [comment]
Looking at the conflicts, it appears that there are file location changes and major differences that won't be easily resolved here. I would prefer to re-implement the csv changes on a new branch that try to reconcile this one.

@aaroncohen73 @subnomo

**Comment by aaroncohen73** [comment]
@Kennric @subnomo @ElijahCaine CSV has been re-implemented in #108

**Pull request closed without merging**
