### PR TITLE
Unicode support

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #34 

## Changes in this PR.

- [X] Unicode characters received from the server display properly
- [X] Unicode characters can be entered and sent to the server
- [x] Update Pymesync to fix password hashing error

## Testing this PR.

1. Select the option `ga` from inside Climesync and see that it doesn't crash when it gets a unicode character
2. Enter a unicode character when creating a time and see that it doesn't crash

@osuosl/devs

### CODE REVIEW

**Comment by ElijahCaine** [comment]
@aaroncohen73 I tried creating a new user on this branch and got the following error:
```
[... successful connecting and auth ...]
(h for help) $ cu
New user username: someusername
New user password: A Password
(Optional) New user display name: My Name
(Optional) New user email: voigte@osuosl.org
(Optional) (y/N) Is the user an admin?: n
(Optional) (y/N) Is the user a manager?: y
(Optional) (y/N) Is the user a spectator?: y
(Optional) Extra meta-information: 
(Optional) (y/N) Is the new user active?: y
Traceback (most recent call last):
  File "./climesync.py", line 841, in <module>
    main()
  File "./climesync.py", line 838, in main
    menu()
  File "./climesync.py", line 795, in menu
    response = create_user()
  File "./climesync.py", line 692, in create_user
    return ts.create_user(user=post_data)
  File "/path/to/climesync/venv/local/lib/python2.7/site-packages/pymesync/pymesync.py", line 268, in create_user
    rounds=10))
  File "/path/to/climesync/venv/local/lib/python2.7/site-packages/bcrypt/__init__.py", line 57, in hashpw
    raise TypeError("Unicode-objects must be encoded before hashing")
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by aaroncohen73** [comment]
@ElijahCaine This looks like something that needs to be fixed with Pymesync's Unicode support. Pymesync frontends should be able to send Unicode objects to Pymesync without encoding them.

**Comment by ElijahCaine** [comment]
+1 passes that informal test that broke before.

**Comment by Kennric** [comment]
+1

**Pull request merged**
