### PR TITLE
Added time summary to get_projects

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #65 
## Changes in this PR.

- [X] The `gp` command now fetches all times submitted under each project and prints out a short summary for each project
## Testing this PR.

1. Run `nosetests`
2. Run climesync, connect to the staging server, and login as "admin" with the password "timesync-staging" 
3. Run `gp`, and when asked for a project slug enter "px". You should see the fields "first_time", "latest_time", "num_times", and "time_total" inside the project.

@osuosl/devs

### CODE REVIEW

**Comment by Kennric** [comment]
Can we sort the fields in the summary? I think this would be a good view:

```
name: CASS Web
slugs: [u'cass-web']
uri: https://github.com/osu-cass/cass-pelican
uuid: 4a47ae3c-5121-445e-ac0e-3f32a092f939
default_activity: None
created_at: 2016-07-08
updated_at: 2016-07-22
deleted_at: None
revision: 5
users: {u'kennric': {u'member': True, u'manager': True, u'spectator': True}, u'mrsj': {u'member': True, u'manager': False, u'spectator': True}, u'leian': {u'member': True, u'manager': False, u'spectator': True}, u'thai': {u'member': True, u'manager': False, u'spectator': True}, u'kelnera': {u'member': True, u'manager': False, u'spectator': True}, u'pam': {u'member': True, u'manager': False, u'spectator': True}}
num_times: 2
first_time: 2016-07-22
latest_time: 2016-07-25
time_total: 5h0m

```

**Comment by ElijahCaine** [comment]
Very cool. :+1: from me.

**Comment by aaroncohen73** [comment]
@Kennric That probably belongs in a separate PR because it would require modifying a fair bit of code

**Comment by Kennric** [comment]
+1

**Pull request merged**
