### PR TITLE
Fixed get time by UUID error

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #40 

## Changes in this PR.

- [X] Fixed issue

## Testing this PR.

1. Run `nosetests` and `flake8 climesync.py`
2. Run the program and provide a value for the `UUID` option inside get_times

@osuosl/devs

### CODE REVIEW

**Comment by Kennric** [comment]
That works. It does seem to point to something non-optimal about how timesync/pymesync works, though... +1

**Comment by aaroncohen73** [comment]
@Kennric I think that this issue has been fixed in the develop branch of Pymesync, but it hasn't been released yet. In the meantime, this code is non-optimal but necessary.

**Comment by mathuin** [comment]
If this issue is already resolved in the develop branch of pymesync but not yet merged with master, will this code need to be reverted once the pymesync fix is merged with master?  Was this code tested against the master branch of pymesync or the develop branch?

This raises questions for @Kennric and @matthewrsj re: the trio of projects and how they should be tested:

Should climesync be tested against an instance of pymesync from the develop branch or the master branch?  Does the branch of timesync matter as well?  Couldn't find anything in the documentation to say one way or the other.

**Comment by aaroncohen73** [comment]
Closing because the bug was fixed in Pymesync

**Pull request closed without merging**
