### PR TITLE
Scripting mode added

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #39 
Also addresses #38

## Changes in this PR.

- [X] Scripting mode added to Climesync

## Testing this PR.

1. Run `nosetests`
2. Run `./climesync.py --help` to see all the command line options
3. Use those command line options to interact with TimeSync

@osuosl/devs

### CODE REVIEW

**Comment by ElijahCaine** [comment]
```
$ ./climesync.py get-times
Traceback (most recent call last):
  File "./climesync.py", line 187, in <module>
    main()
  File "./climesync.py", line 181, in main
    scripting_mode(command, argv)
  File "./climesync.py", line 149, in scripting_mode
    util.print_json(command(argv))
  File "/home/voigte/gitsrc/other/climesync/commands.py", line 33, in wrapped_command
    return command(post_data)
  File "/home/voigte/gitsrc/other/climesync/commands.py", line 289, in get_times
    if 'error' not in times[0] and 'pymesync error' not in times[0]:
IndexError: list index out of range
```

**Comment by ElijahCaine** [comment]
```
¡ ./climesync.py get-projects --slug=iam

pymesync error: invalid combination: slug and include_deleted
```

**Comment by ElijahCaine** [comment]
This PR needs some work @aaroncohen73.

**Comment by Kennric** [comment]
This is looking pretty good, I will run it through its paces as much as I can.

@mathuin @subnomo @alxngyn @athai - please also try this out.

**Comment by mathuin** [comment]
Checked out PR, ran `python setup.py build`, ran `python setup.py install --user`, got following traceback:

```
Running mock-1.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-4H70vJ/mock-1.3.0/egg-dist-tmp-j_Yvjc
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 382, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 132, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-4H70vJ/mock-1.3.0/setup.cfg: TypeError: dist must be a Distribution instance
```

**Comment by mathuin** [comment]
Ken helped me get a virtualenv up with this code.  When I ran climesync.py, it asked about URL, I gave the right one, and I got this traceback:

```
(climesync) (osuosl-cohenaa/scripting=) jmt@emerald:~/git/climesync$ ./climesync.py 
URL of TimeSync server: https://timesync.osuosl.org/v0
> timesync_url = https://timesync.osuosl.org/v0
(Optional) (y/N) Add to the config file?: y
Traceback (most recent call last):
  File "./climesync.py", line 193, in <module>
    main()
  File "./climesync.py", line 173, in main
    interactive=interactive)
  File "/home/jmt/git/climesync/commands.py", line 62, in connect
    util.add_kv_pair("timesync_url", url)
  File "/home/jmt/git/climesync/util.py", line 235, in add_kv_pair
    write_config(key, value, path)
  File "/home/jmt/git/climesync/util.py", line 57, in write_config
    create_config(path)
  File "/home/jmt/git/climesync/util.py", line 18, in create_config
    os.chmod(realpath, stat.S_IRUSR, stat.S_IWUSR)
TypeError: chmod() takes exactly 2 arguments (3 given)
(climesync) (osuosl-cohenaa/scripting=) jmt@emerald:~/git/climesync$ 
```

**Comment by aaroncohen73** [comment]
@mathuin Should be fixed now

**Comment by mathuin** [comment]
The config file traceback has indeed been resolved.  If the other issue (install --user) is out of scope for your pull request, then you have my +1

**Comment by aaroncohen73** [comment]
@mathuin It looks like the other issue is out of the scope of this PR. The error seems to happen when the `mock` library is being installed as a dependency of Pymesync.

**Comment by Kennric** [comment]
+1

**Pull request merged**
