### PR TITLE
Update object commands now print current object values

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #61 

## Changes in this PR.

- [X] `ut`, `up`, `ua`, and `uu` now all show the current time/project/activity/user before asking the user for updated values

## Testing this PR.

1. Run climesync and sign in as `admin` with the password `timesync-staging`
2. Run `gt` without filter options and copy the UUID of any time
3. Run `ut` and paste the UUID of the time you copied
4. See that the current revision of the time is printed
5. Repeat the above steps for project/slug, activity/slug, and user/username

@osuosl/devs

### CODE REVIEW

**Comment by Kennric** [comment]
That helps, I was hoping for the values to appear list default options in each field prompt, like:

```
Updated project name [Streamwebs]: 
(Comma delimited) Updated project slugs [sw, streams, streamwebs]: 
Updated project URI [https://github.com/osuosl/streamwebs/]: 
(Comma delimited) Updated users [kennric, leian, thai, patcht]: 
Updated default activity [None]: 
```

I know that's significantly more work to implement, but I think very helpful. The current approach will work if adding values to prompts is going to be an enormous task.

**Comment by aaroncohen73** [comment]
@Kennric That's definitely doable.

**Comment by Kennric** [comment]
This looks great. As soon as it is rebased, I'll approve.

**Comment by Kennric** [comment]
+1

**Comment by ElijahCaine** [comment]
First off, feel free to update the PR description/instructions to reflect any changes you've made. I was expecting the object to be printed before the changes. I like the current value being the default, but I was confused for minute.

Anyway, this is a good change. :+1: from me.

**Pull request merged**
